# Generated by Django 2.0.2 on 2018-04-22 13:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('los_angeles', django.db.models.manager.Manager()),
            ],
        ),
    ]
